const products = [
    {
        id: 1,
        title: "Minimalist Wallet",
        description: "Slim and lightweight wallet made from high-quality materials. Perfect for everyday use.",
        img_url: "https://picsum.photos/id/151",
        price: 850,
    },
    {
        id: 2,
        title: "Stainless Water Bottle",
        description: "Insulated stainless steel water bottle that keeps drinks cold or hot for hours.",
        img_url: "https://picsum.photos/id/152",
        price: 650,
    },
    {
        id: 3,
        title: "Laptop Sleeve",
        description: "Protective laptop sleeve with soft interior padding and water-resistant exterior.",
        img_url: "https://picsum.photos/id/153",
        price: 1200,
    },
    {
        id: 4,
        title: "Wireless Charging Pad",
        description: "Fast wireless charging pad compatible with most smartphones and earbuds.",
        img_url: "https://picsum.photos/id/154",
        price: 1400,
    },
    {
        id: 5,
        title: "Desk Lamp",
        description: "Modern LED desk lamp with adjustable brightness and eye-protection technology.",
        img_url: "https://picsum.photos/id/155",
        price: 1750,
    },
    {
        id: 6,
        title: "Mechanical Keyboard",
        description: "High-performance mechanical keyboard with tactile switches and durable build.",
        img_url: "https://picsum.photos/id/156",
        price: 3900,
    },
    {
        id: 7,
        title: "Fitness Tracker",
        description: "Track your steps, heart rate, sleep, and daily activities with ease.",
        img_url: "https://picsum.photos/id/157",
        price: 2500,
    },
    {
        id: 8,
        title: "Canvas Tote Bag",
        description: "Eco-friendly canvas tote bag ideal for shopping, school, or casual outings.",
        img_url: "https://picsum.photos/id/158",
        price: 700,
    },
    {
        id: 9,
        title: "Portable Power Bank",
        description: "High-capacity power bank for charging devices on the go with fast charging support.",
        img_url: "https://picsum.photos/id/159",
        price: 2300,
    },
    {
        id: 10,
        title: "Noise-Isolating Earbuds",
        description: "Compact earbuds offering clear sound and effective noise isolation.",
        img_url: "https://picsum.photos/id/160",
        price: 1600,
    },
    {
        id: 11,
        title: "Leather Key Organizer",
        description: "Compact leather key organizer that keeps your keys silent, organized, and scratch-free.",
        img_url: "https://picsum.photos/id/161",
        price: 480,
    },
    {
        id: 12,
        title: "USB-C Hub Adapter",
        description: "Multi-port USB-C hub with HDMI, USB 3.0, and SD card support for modern laptops.",
        img_url: "https://picsum.photos/id/162",
        price: 1900,
    },
    {
        id: 13,
        title: "Foldable Phone Stand",
        description: "Portable and foldable phone stand ideal for video calls, streaming, and desk use.",
        img_url: "https://picsum.photos/id/163",
        price: 350,
    },
    {
        id: 14,
        title: "Noise Cancelling Headphones",
        description: "Over-ear headphones with active noise cancelling and immersive sound quality.",
        img_url: "https://picsum.photos/id/164",
        price: 4200,
    },
    {
        id: 15,
        title: "Smart LED Light Bulb",
        description: "WiFi-enabled smart LED bulb controllable via mobile app or voice assistant.",
        img_url: "https://picsum.photos/id/165",
        price: 900,
    },
    {
        id: 16,
        title: "Anti-Theft Backpack",
        description: "Secure backpack with hidden zippers and USB charging port for daily commuting.",
        img_url: "https://picsum.photos/id/166",
        price: 2600,
    },
    {
        id: 17,
        title: "Portable Mini Fan",
        description: "Rechargeable mini fan perfect for travel, desk use, or outdoor activities.",
        img_url: "https://picsum.photos/id/167",
        price: 520,
    },
    {
        id: 18,
        title: "Gaming Mouse Pad",
        description: "Large mouse pad with smooth surface and non-slip rubber base for precision control.",
        img_url: "https://picsum.photos/id/168",
        price: 750,
    },
    {
        id: 19,
        title: "Digital Alarm Clock",
        description: "Modern digital alarm clock with LED display and multiple alarm settings.",
        img_url: "https://picsum.photos/id/169",
        price: 980,
    },
    {
        id: 20,
        title: "Wireless Mouse",
        description: "Ergonomic wireless mouse with adjustable DPI and long battery life.",
        img_url: "https://picsum.photos/id/170",
        price: 1100,
    },

    {
        id: 21,
        title: "Laptop Cooling Pad",
        description: "Cooling pad with silent fans to prevent laptop overheating during heavy use.",
        img_url: "https://picsum.photos/id/171",
        price: 1450,
    },
    {
        id: 22,
        title: "Smart Plug",
        description: "Control your appliances remotely using this WiFi-enabled smart plug.",
        img_url: "https://picsum.photos/id/172",
        price: 850,
    },
    {
        id: 23,
        title: "Bluetooth Car Adapter",
        description: "Hands-free Bluetooth adapter for car audio systems with clear call quality.",
        img_url: "https://picsum.photos/id/173",
        price: 1250,
    },
    {
        id: 24,
        title: "Desk Organizer Set",
        description: "Minimalist desk organizer set to keep your workspace tidy and efficient.",
        img_url: "https://picsum.photos/id/174",
        price: 1600,
    },
    {
        id: 25,
        title: "Reusable Coffee Cup",
        description: "Eco-friendly reusable coffee cup made from heat-resistant materials.",
        img_url: "https://picsum.photos/id/175",
        price: 600,
    },
    {
        id: 26,
        title: "Tripod Stand",
        description: "Adjustable tripod stand suitable for smartphones, cameras, and ring lights.",
        img_url: "https://picsum.photos/id/176",
        price: 1350,
    },
    {
        id: 27,
        title: "Smart Digital Scale",
        description: "Digital weighing scale with BMI tracking and mobile app support.",
        img_url: "https://picsum.photos/id/177",
        price: 2100,
    },
    {
        id: 28,
        title: "Wireless Doorbell",
        description: "Easy-to-install wireless doorbell with multiple chime options.",
        img_url: "https://picsum.photos/id/178",
        price: 950,
    },
    {
        id: 29,
        title: "Foldable Travel Umbrella",
        description: "Lightweight and wind-resistant umbrella perfect for daily and travel use.",
        img_url: "https://picsum.photos/id/179",
        price: 720,
    },
    {
        id: 30,
        title: "Electric Kettle",
        description: "Fast-boiling electric kettle with auto shut-off and sleek design.",
        img_url: "https://picsum.photos/id/180",
        price: 2400,
    },
]

export default products;